- name: Deploy Dockerized E-commerce App
  hosts: ec2
  become: true
  vars_files:
    - vars.yml 

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.yum:
        name: docker
        state: present

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Stop and remove old container (if exists)
      community.docker.docker_container:
        name: ecommerce-app
        state: absent

    - name: Pull latest image from Docker Hub
      community.docker.docker_image:
        name: mnagy156/ecommerce-app
        tag: latest
        source: pull

    - name: Run container
      community.docker.docker_container:
        name: ecommerce-app
        image: mnagy156/ecommerce-app:latest
        ports:
          - "80:8080"
        state: started
