pipeline {
  agent any
  environment {
    DOCKER_HUB_PASSWORD = credentials('docker-hub-password') // Secret text
  }
  stages {
    stage('Deploy via Ansible') {
      steps {
        withCredentials([file(credentialsId: 'spring-ec2-key', variable: 'KEY')]) {
          dir('ci_cd') {
            sh """
              ansible-playbook -i ../infra/ansible/hosts.ini ../infra/ansible/deploy_app.yml \
              --private-key "$KEY" \
              --extra-vars "docker_hub_password=${DOCKER_HUB_PASSWORD}" \
              -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
            """
          }
        }
      }
    }
  }
}
